eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    preferIpAddress: 'true'
spring:
  application:
    name: API-GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: EMAIL-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/api/email/**
          filters:
            - AuthenticationFilter

        - id: ORDER-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter

        - id: AUTH-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/api/userEntity/**, /api/auth/**

server:
  port: '9090'




